[33ma4a3bcc[m[33m ([m[1;36mHEAD -> [m[1;32maryan[m[33m, [m[1;31morigin/master[m[33m, [m[1;32mmaster[m[33m)[m reverted
[33mfa9c294[m seventh
[33m2faf613[m finally
[33mf6c5c72[m masla
[33m4d84e17[m sixth commit
[33m8f0b195[m fifth commit
[33m1fa5dde[m forth commit
[33m9478b87[m staging commit
[33m78c3296[m Third commit
[33mc692189[m second commit
[33mbdd411b[m Initial commit
